version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sales-network

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/auth_db?sslmode=disable
    depends_on:
      - db
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge

volumes:
  postgres_data:
