# Server Configuration
port: "8080"

# Database Configuration
database:
  host: db.spjqkrsbpwwitwldksvt.supabase.co
  port: 5432
  user: postgres
  password: 1234winnie
  name: postgres
  sslmode: require
  # Additional connection parameters
  connect_timeout: 10
  prefer_simple_protocol: true
  # Timeout settings
  statement_timeout: 30000
  idle_in_transaction_session_timeout: 30000

# JWT Configuration
jwt_secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

# SMTP Configuration
smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "abhishekbrichhaliya@gmail.com"
  pass: "dbzg lsna gzdm qxyy"
  from: "noreply@sales-tracker.com"
  from_name: "Sales Tracker Team"

# Application URLs
base_url: "http://localhost:8080"
password_reset_path: "/auth/reset-password.html"
verification_path: "/auth/verify"
